# Generated by Django 5.1.1 on 2024-10-07 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_active', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('riding_style', models.CharField(blank=True, max_length=20, null=True)),
                ('favourite_place_to_ride', models.CharField(blank=True, max_length=50, null=True)),
                ('local_trails', models.CharField(blank=True, max_length=50, null=True)),
                ('bike', models.CharField(blank=True, max_length=50, null=True)),
                ('favourite_conditions', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
